version: "3.5"
services:
  kc1:
    image: keycloak_full-export:4.3.0.Final
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: H2
    ports:
      - 9080:8080
  kc2:
    image: keycloak_full-export:4.3.0.Final
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: H2
    ports:
      - 9081:8080
